### PR TITLE
Crashing bug

### PR DESCRIPTION
**Pull request by AlexaderDNT**
It crash the project with at extra !

### CODE REVIEW

**Comment by jason-adnuntius** [comment]
This change causes errors in Xcode 13.4, I cannot merge it.

**Comment by jason-adnuntius** [comment]
I am upgrading to 13.4.1 to see if I get the same issue as you.  Alternatively please post what version of XCode you are using (and whether you are on intel or apple silicon), just so I can narrow down the problem.

**Comment by AlexaderDNT** [comment]
I am using xcode version 13.4.1 and macOS Monterey macbook pro 2019 inter core i9

From: Jason Pell ***@***.***>
Date: Tuesday, 5 July 2022 at 11:17
To: Adnuntius/ios_sdk ***@***.***>
Cc: Alexander Larsen ***@***.***>, Author ***@***.***>
Subject: Re: [Adnuntius/ios_sdk] Crashing bug (PR #18)

I am upgrading to 13.4.1 to see if I get the same issue as you. Alternatively please post what version of XCode you are using (and whether you are on intel or apple silicon), just so I can narrow down the problem.

**Comment by jason-adnuntius** [comment]
Ok, well on an M1 with same xcode version it does not cause the same issue, and applying your change causes problems.  I think I have an idea that might resolve it for both.

can you provide the actual error message that you get in your xcode?

**Comment by jason-adnuntius** [comment]
Can you try this change instead?

```
-            guard let adUnits = responseJSON!!["adUnits"] as? [[String: Any]] else {
+            guard let adUnits = (responseJSON!)!["adUnits"] as? [[String: Any]] else {
```

**Comment by jason-adnuntius** [comment]
Closing in favour of https://github.com/Adnuntius/ios_sdk/pull/19

**Pull request closed without merging**
