### PR TITLE
Add SPM

### PR DESCRIPTION
**Pull request by AlexIzh**
#6

### CODE REVIEW

**Comment by jason-adnuntius** [comment]
For now, I won't be merging this.  See my comments on the issue you opened.   If SPM can support Objective-C, and we can get the example projects migrated to use it, I would consider it.

**Comment by AlexIzh** [comment]
We are using our fork with SPM supporting for this repository and it works fine

**Comment by jason-adnuntius** [comment]
Can you share any details of how to integrate the SPM version of the SDK into an application?   Will carthage still work even with this merged?

**Comment by AlexIzh** [comment]
Yes, as I has answered on the issue, SPM doesn't conflict with SPM. Your library could contains all package managers from the iOS world (cocoa pods, spm, Carthage, anything else) and a client will decide what they want to use. To support SPM everything what you need, is to add Package.swift file (as in this PR) and now you support 2 different managers and clients have a choice, they could use either Carthage or SPM if they want to. 

To integrate SPM package to your application, you need to open "Xcode -> File -> Package Dependencies -> Add Package Dependency" and just insert an url to GitHub page of the package/library, that's all.

**Pull request merged**
